@startuml

frame ViewRecord {
  component ClientApplication as "Client Application"
}

interface facade as "[[CapabilityStatement-VH-ClinicalDataRepository.html Clinical Data Sharing API\n(Internal+External)]]"

component "[[ActorDefinition-ClinicalDataRepository.html Clinical Data Repository]]" as CDR

component "[[ActorDefinition-EventSource.html Event Source]]" as EventSource

frame DataCapture {
  component "Data Capture Application" as sdc

  component "Data Extraction Service" as sdcExtract
  component "Pre-populate Service" as sdcPrePopulate
}

interface "Incoming Events\n(Internal+External)" as EventServiceIn

component "[[ActorDefinition-EventConsumer.html Event Consumer]]" as EventConsumer

interface "Outgoing Events\n(Internal+External)" as EventServiceOut

CDR -u-> facade

facade -u-> ClientApplication

EventSource -r-> EventServiceIn
EventServiceIn -r-> CDR

CDR -r-> EventServiceOut
EventServiceOut -r-> EventConsumer

sdc <-d- sdcPrePopulate
sdcPrePopulate <-d- facade

sdc -d-> sdcExtract
sdcExtract -d-> CDR





@enduml
