@startuml

component ClientApplication as "Client Application"

interface facade as "[[CapabilityStatement-VH-ClinicalDataRepository.html Clinical Data Sharing API]]"

component "[[ActorDefinition-ClinicalDataRepository.html Clinical Data Repository]]" as CDR

component "[[ActorDefinition-EventSource.html Event Source]]" as EventSource

interface "Incoming Events" as EventServiceIn

component "[[ActorDefinition-EventConsumer.html Event Consumer]]" as EventConsumer

interface "Outgoing Events" as EventServiceOut

CDR -u-> facade

facade -u-> ClientApplication

EventSource -r-> EventServiceIn
EventServiceIn -r-> CDR

CDR -r-> EventServiceOut
EventServiceOut -r-> EventConsumer




@enduml
