
  @startuml

    skinparam svgDimensionStyle false

    component "Online Consultation\n**Data Capture**" as triage

    frame "Device Data Capture" as phr {
      component "Apple Health" as Apple
      component "Google Health" as Google
    }

    frame "Patient Care Coordination" as community {
    component "Referrals, Consultation Writeback \nand Discharge Reports" as bars
    }

    frame "Primary Care" as pc {
      component "Clinical Data Repository" as im1 <<database>>
    }
    component "Patient Observatory\n**Clinical Decision Support**" as obs

    component "**Clinical Data Repository**" as CDR <<database>>

    component "**Clinical and Finanicial Analytics**\nPopulation Management\nand Health Insights" as omop <<data warehouse>>

    component "Clinical Portal\n**Health Information Exchange**" as HIE

    component "National Record Locator\n**Health Document Sharing (XDS)**" as XDS

    component "National Analytics\nFederated Data Platform" as FDP  <<data warehouse>>

    interface "Commissioning\nData Sets\nQOF Data" as QOF

    triage --> CDR  : [[https://build.fhir.org/ig/HL7/sdc/ FHIR Structured Data Capture]]
    Apple --> obs
    Google --> obs

    obs <--> CDR : FHIR RESTful\n+ SQL

    bars <--> CDR: FHIR RESTful

    im1 --> CDR : IM1 Bulk, ETL + \n[[https://hl7.org/fhir/uv/bulkdata/ FHIR Bulk Data]]

    CDR --> omop : ETL

    HIE <-r- CDR: FHIR [[https://build.fhir.org/ig/HL7/fhir-ipa/ IPA]]

    XDS <-l- CDR: [[https://en.wikipedia.org/wiki/EN_13606 ISO13606]]\nFHIR [[https://build.fhir.org/ig/HL7/fhir-ips/index.html IPS]] + EU

    omop --> FDP: ETL

    QOF -r-> FDP

    note as OMOP
      Future?
      AI Ready
      OMOP and [[ OHDSI]]
    end note

    note as FHIR
      Based on HL7 FHIR [[artifacts.html#5 Data Model]]
      ISO 13972 / [[https://build.fhir.org/ig/Xt-EHR/xt-ehr-common/artifacts.html EU EHDS]]
      plus [[https://www.datadictionary.nhs.uk/ NHS Data Model and Dictionary]]
      AI Ready
    end note

    OMOP .l. omop
    FHIR .l. CDR

  @enduml
