@startmindmap

skinparam svgDimensionStyle false

title "Consultation Note (online and pharmacy)"

* [[Questionnaire-ConsultationNote.html Consultation Note]] **template**
** Subjective
*** Complaints and Issues (61150-9)\nPresenting complaints or issues (PRSB)
**** [[StructureDefinition-Observation.html Observation]]
**** Attachments ([[StructureDefinition-DocumentReference.html DocumentReference]] + Binary)
** Objective\n(ADPIE Assement)
*** Examination findings (PRSB)
**** [[Questionnaire-VitalSigns.html Vital Signs (8716-3)]] <b>archetype</b>
***** [[StructureDefinition-Observation.html Observation (category=vital-signs]]
**** [[Questionnaire-DailyPhysicalActivity.html Physical Activity]] **template**
***** [[StructureDefinition-Observation.html Observation (category=activity)]]
**** [[StructureDefinition-Observation.html Observation (category=exam)]]
*** Social History (29762-2)\nSocial Context (PRSB)
**** Social History TODO <b>template</b>
***** [[StructureDefinition-Observation.html Observation (category=social-history)]]
*** Family History (10157-6)
**** Family History TODO <b>template</b>
** Assessment\n(ADPIE Diagnose)
*** Assessment (51848-0)\nClinical risk factors (PRSB)
**** [[StructureDefinition-ClinicalImpression.html ClinicalImpression]]
**** [[StructureDefinition-Observation.html Observation (category=survey?)]]
*** Problem (11450-4)\nProblem List (PRSB)
**** [[StructureDefinition-Condition.html Condition]]
** Plan\n(ADPIE Plan)
*** Care Plan (18776-5)\nProfessional contacts (PRSB)\nPlan and requested actions(PRSB)
**** [[StructureDefinition-CarePlan.html Care Plan]]
***** Safeguarding (PRSB)
***** Signpost details (PRSB)
**** [[StructureDefinition-CareTeam.html Care Team]]
**** [[StructureDefinition-Goal.html Goal]]
** Plan\n(ADPIE Implement)
*** Vaccination (PRSB)
**** [[StructureDefinition-Immunization.html Immunization]]
*** Referral Details (PRSB)
**** [[StructureDefinition-ServiceRequest.html ServiceRequest]]
*** Medications (PRSB)
**** [[StructureDefinition-MedicationRequest.html MedicationRequest]]
*** Investigation
**** [[StructureDefinition-ServiceRequest.html ServiceRequest]]

@endmindmap
