@startuml

skinparam svgDimensionStyle false

frame PD1 as "Patient" {
class "[[StructureDefinition-Patient.html Patient]]" as Patient <<aggregate root>> {
identifier 1..* : PatientIdentifier
name
gender
birthDate
address
telecom
address
}


class PatientIdentifier <<entity>> {
NHSNumber 0..1
CHINumber 0..1
MedicalRecordNumber (EMIS, TPP, Hospital Number, etc)
}

Patient "identifier" --> PatientIdentifier

}

frame Diagnostics as "Diagnostics" {
class "[[StructureDefinition-Observation.html Observation]]" as Observation <<entity>> {
identifier 1..*
subject 1..1: PatientIdentifier
code : UK SNOMED CT or LOINC
effectiveDateTime
value[x]: codes are UK SNOMED CT or LOINC
encounter 0..1
}


class "[[assessments-and-observations.html Observation Panel]]" as ObservationPanel <<entity>> {
identifier 1..*
subject 1..1: PatientIdentifier
code : UK SNOMED CT or LOINC
effectiveDateTime
hasMember: 1..*: Observation
encounter 0..1
}


class "[[StructureDefinition-DiagnosticReport.html Diagnostic Report]]" as DiagnosticReport <<aggregate root>> {
identifier 1..*
basedOn 0..1: AccessionNumber
subject: PatientIdentifier
code : UK SNOMED CT or LOINC
effectiveDateTime
result: ObservationPanel and Observation
presentedForm 0..* : Attachment
}

DiagnosticReport "result" --> ObservationPanel
ObservationPanel "hasMember" --> Observation

}


frame DataCapture as "Archetype" {

class "[[StructureDefinition-QuestionnaireResponse.html Form]]" as Form <<data transfer object>> {
identifier 1..1
subject
questionnaire 0..1 : Questionnaire
code : (in FHIR from Questionnaire)
authored 1..1 : DateTime
answers 1..*
}



class "[[StructureDefinition-Questionnaire.html Form Definition]]" as FormDefinition <<aggregate root>> {
identifier 1..1
url
code : UK SNOMED CT or LOINC
questions 1..*
}

FormDefinition "url" -d-|> "questionnaire" Form : defintion

}

frame Documents {

class Attachment <<entity>> {
contentType: (also mimeType and file extension)
title
languageCode
data: file contents
}


class "[[StructureDefinition-DocumentReference.html Document Entry]]" as DocumentEntry <<aggregate root>> {
category: UK SNOMED CT
type : UK SNOMED CT
subject : PatientIdentifier
attachment 1..*
referenceIdList : AccessionNumber (FHIR context.related)
}


DocumentEntry "attachment" -d-> Attachment

}

frame Orders {

class "Laboratory/Imaging Order" as labOrder <<aggregate root>> {
accessionNumber 1..1 : AccessionNumber
filerOrderNumber 1..1: Identifier
placerOrderNumber 1..1 : Identifier
subject: PatientIdentifier
code: Procedure code UK SNOMED CT, LOINC or NICIP
}

class AccessionNumber <<value>> {

}

class "Prescription (MedicationeRequest)" as Prescription <<aggregate root>> {
identifier 1..*
subject: PatientIdentifier
medication: UK SNOMED CT (dm+d)
}


class "Referral" as Referral <<aggregate root>> {
identifier 1..*
subject: PatientIdentifier
code: Procedure code UK SNOMED CT
}

labOrder -d[hidden]- Prescription
Prescription -d[hidden]- Referral


labOrder "accessionNumber" --> AccessionNumber

}


DocumentEntry "referenceIdList" --|> AccessionNumber
DiagnosticReport "basedOn" --|> AccessionNumber



Observation "subject" --|> PatientIdentifier
ObservationPanel "subject" --|> PatientIdentifier
DiagnosticReport "subject" --|> PatientIdentifier
DocumentEntry "subject" --|> PatientIdentifier
Form "subject" --|> PatientIdentifier
labOrder "subject" -u-|> PatientIdentifier
Referral "subject" -u-|> PatientIdentifier
Prescription "subject" -u-|> PatientIdentifier


Form "answers" --|> Observation : data extraction
Form "code and answers" --|> ObservationPanel: data extraction


DiagnosticReport "attachment" --> Attachment

@enduml
