@startuml


title "Referral Request (PCC-55)"

hide footbox

participant "Referral Initiator" as placer
participant "Enterprise Document/Data Sharing" as XDS
participant "Referral Recipient" as filler


placer -> XDS : [[I12.html Referral Request (PCC-55)]]
placer -> filler: REF_I12 Command Message
filler -> XDS: Retrieve [[I12.html Referral Request (PCC-55)]]

@enduml
