@startmindmap

title "Shared Patient Records"

* [[StructureDefinition-PatientSummary.html Patient Summary]]
** Problem (11450-4)
** Allergy (48765-2)
** Medication (10160-0)
** etc
* Patient Record Detail
** [[StructureDefinition-AllergyIntolerance.html AllegyIntolerance]]
** Condition
** [[StructureDefinition-DiagnosticReport.html DiagnosticReport]] (Laboratory reports)
** [[StructureDefinition-DocumentReference.html DocumentReference]] (index of documents)
*** Binary (documents)
** [[StructureDefinition-Encounter.html Encounter]]
*** Composition ([[StructureDefinition-ConsulationNote.html Consultation Notes]])
** [[StructureDefinition-Immunization.html Immunization]]
** [[StructureDefinition-MedicationRequest.html MedicationRequest]] (prescriptions)
** [[StructureDefinition-Observation.html Observation]]
** [[StructureDefinition-Patient.html Patient]] (demographics)
** [[StructureDefinition-QuestionnaireResponse.html QuestionnaireResponse]] Templates/Forms/Assessments
** [[StructureDefinition-ServiceRequest.html ServiceRequest]] (referrals and laboratory orders)

@endtmindmap
