@startuml

hide footbox

title "Shared Patient Record - Practitioner Local Patient"

participant "Practitioner" as practitioner
participant "PDS" as pds
participant "GP Connect (html)" as GPC
participant "EMIS IM1" as IM1
participant "VH CDR" as CDR

practitioner -> pds : Lookup Patient
== Patient GP Practice is using EMIS IM1 ==
practitioner -> GPC: Retrieve Patient Summary Record
opt as required by practitioner
practitioner -> IM1: Retrieve detailed record
practitioner -> CDR: Retrieve detailed record\nOnly for entities not covered by EMIS IM1
end

@enduml
