@startmindmap

title "Social Determinants of Health"

* Social Determinants of Health
** Smoking use
** Alcohol use
** Drug/substance use
** Social circumstances
** Accommodation status
** Occupation
** Education

@endmindmap
